# Default values for cosmocloud-deploy
backend:
  image: shreybatra/sample-backend
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8000

frontend:
  image: shreybatra/sample-frontend
  replicaCount: 1
  service:
    type: NodePort
    port: 5173
    nodePort: 31000

redis:
  image: redis
  replicaCount: 1
  service:
    type: ClusterIP
    port: 6379